# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igSJ_GhQsSIiUJ1v51LAAPLCWAd5L5MQ

Import Necessary Libraries
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
from sklearn.feature_selection import VarianceThreshold
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score,f1_score
from sklearn.metrics import confusion_matrix
import joblib
import shutil
from google.colab import files

"""Load Dataset"""

from google.colab import drive
drive.mount('/content/drive')
data = pd.read_csv('/content/drive/My Drive/SQLi/SQL_dataset.csv')

"""Data cleaning and preprocessing"""

# Stage 1: Convert text into a collection of words
vectorizer = CountVectorizer(lowercase=False)
X = vectorizer.fit_transform(data['Query'])
# Stage 2: Remove frequently and infrequently used terms
sel = VarianceThreshold(threshold=(.0001 * (1 - .0001)))
X = sel.fit_transform(X)
# Stage 3: Convert every word into lowercase
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data['Query'].str.lower())
y = data['Label']
# Stage 4: Remove missing rows
data.dropna(inplace=True)

"""Splitting dataset"""

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42)

"""Training & Testing"""

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42)
# Creating and Training the Model
model = LogisticRegression(max_iter=1000, solver='liblinear') # liblinear is more efficient for large sparse data
model.fit(X_train, y_train)
# Making predictions on the test set
y_pred = model.predict(X_test)
# Evaluating the Model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")
print(f"Precision: {precision*100:.2f}%")
print(f"Recall: {recall*100:.2f}%")
print(f"F1 Score: {f1*100:.2f}%")
print(classification_report(y_test, y_pred))

"""Confusion Matrix"""

conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
xticklabels=['Positive', 'Negative'], yticklabels=['Positive', 'Negative'])
plt.xlabel('Predictions')
plt.ylabel('Actual Values')
plt.title('Confusion Matrix')
plt.show()

"""Testing with new Dataset"""

# Load the new dataset
new_data_path = '/content/drive/My Drive/SQLi/New_SQL_dataset.csv'
new_data = pd.read_csv(new_data_path)
# Preprocessing to the new dataset
new_X = vectorizer.transform(new_data['Query'])
new_y = new_data['Label']
# Predict using the trained model
new_predictions = model.predict(new_X)
# Evaluate the model on the new dataset
new_accuracy = accuracy_score(new_y, new_predictions)
new_precision = precision_score(new_y, new_predictions)
new_recall = recall_score(new_y, new_predictions)
new_f1 = f1_score(new_y, new_predictions)
print(f"New Data_Accuracy: {new_accuracy*100:.2f}%")
print(f"New Data_Precision: {new_precision*100:.2f}%")
print(f"New Data_Recall: {new_recall*100:.2f}%")
print(f"New Data_F1 Score: {new_f1*100:.2f}%")
# Confusion Matrix for the new dataset
new_conf_matrix = confusion_matrix(new_y, new_predictions)
sns.heatmap(new_conf_matrix, annot=True, fmt='d', cmap='Blues',
xticklabels=['Positive', 'Negative'], yticklabels=['Positive', 'Negative'])
plt.xlabel('Predictions')
plt.ylabel('Actual Values')
plt.title('Confusion Matrix for New Dataset')
plt.show()

"""Save and Export"""

# Save the model
joblib.dump(model, 'ML_model.pkl')
# Define path
colab_model_path = 'ML_model.pkl'
# Download the model file
files.download(colab_model_path)
# Save the vectorizer
joblib.dump(vectorizer, 'vectorizer-2.joblib')
# Define path
colab_vectorizer_path = 'vectorizer-2.joblib'
# Download the vectorizer file
files.download(colab_vectorizer_path)